
function Rndm_generate() {
    let num = Math.random() * 50 + 1;
    num = Math.floor(num);
    // To view random number generated uncomment below line
    // console.log(num);
    return num;
}




function check() {
    
    
    // random store random number generated by function
    var random = parseInt(Rndm_generate());
    console.log("Random number is : " + random);



    /*User name fetching start here*/
    // it fetch usre name from sessionStorage. If it is null input user name and set in session storage else display user name from session storage



    let user_name = sessionStorage.getItem('name');
    console.log('Session storage name value is : ' + user_name);

    if (user_name == null) {

        user_name = prompt("Enter user name : ");
        sessionStorage.setItem('name', user_name);
    }

    /* User name fetching ends here */


    let user_input,counter = 0;
    do {
        counter++;
        user_input = parseInt(prompt('Enter the number : '));


        if(random > user_input)
            alert('Try Greater Number.');
        else if(random < user_input)
            alert('Try Smaller Number.');
    } while (random !== user_input);



    let cong_msg = `Congratulations!
You Guessed the Right Answer in ${counter} attempts`;

    let result_html = `Congratulations <strong>${user_name}</strong>!<br>
You Guessed the Right Answer in <strong>${counter}</strong> attempts.`


    // displaying results
    alert(cong_msg);
    document.getElementById("result").innerHTML = result_html;



    setTimeout(() => {
        location.reload();
    }, 5000);

}



// local storage